name: Scrape Table Sums

on: [push]

jobs:
  scrape-table-sums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright and dependencies
        run: npm install playwright
      - name: Scrape Tables and Print Sum - 23f3004152@ds.study.iitm.ac.in
        run: node scrape_tables.js
